// Generated by gencpp from file simple_control/toggle_cage.msg
// DO NOT EDIT!


#ifndef SIMPLE_CONTROL_MESSAGE_TOGGLE_CAGE_H
#define SIMPLE_CONTROL_MESSAGE_TOGGLE_CAGE_H

#include <ros/service_traits.h>


#include <simple_control/toggle_cageRequest.h>
#include <simple_control/toggle_cageResponse.h>


namespace simple_control
{

struct toggle_cage
{

typedef toggle_cageRequest Request;
typedef toggle_cageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct toggle_cage
} // namespace simple_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::simple_control::toggle_cage > {
  static const char* value()
  {
    return "e06196d4192ed08fc72383b1573c2db2";
  }

  static const char* value(const ::simple_control::toggle_cage&) { return value(); }
};

template<>
struct DataType< ::simple_control::toggle_cage > {
  static const char* value()
  {
    return "simple_control/toggle_cage";
  }

  static const char* value(const ::simple_control::toggle_cage&) { return value(); }
};


// service_traits::MD5Sum< ::simple_control::toggle_cageRequest> should match
// service_traits::MD5Sum< ::simple_control::toggle_cage >
template<>
struct MD5Sum< ::simple_control::toggle_cageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::simple_control::toggle_cage >::value();
  }
  static const char* value(const ::simple_control::toggle_cageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::simple_control::toggle_cageRequest> should match
// service_traits::DataType< ::simple_control::toggle_cage >
template<>
struct DataType< ::simple_control::toggle_cageRequest>
{
  static const char* value()
  {
    return DataType< ::simple_control::toggle_cage >::value();
  }
  static const char* value(const ::simple_control::toggle_cageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::simple_control::toggle_cageResponse> should match
// service_traits::MD5Sum< ::simple_control::toggle_cage >
template<>
struct MD5Sum< ::simple_control::toggle_cageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::simple_control::toggle_cage >::value();
  }
  static const char* value(const ::simple_control::toggle_cageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::simple_control::toggle_cageResponse> should match
// service_traits::DataType< ::simple_control::toggle_cage >
template<>
struct DataType< ::simple_control::toggle_cageResponse>
{
  static const char* value()
  {
    return DataType< ::simple_control::toggle_cage >::value();
  }
  static const char* value(const ::simple_control::toggle_cageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIMPLE_CONTROL_MESSAGE_TOGGLE_CAGE_H
