// Generated by gencpp from file sensor_simulation/calibrateRequest.msg
// DO NOT EDIT!


#ifndef SENSOR_SIMULATION_MESSAGE_CALIBRATEREQUEST_H
#define SENSOR_SIMULATION_MESSAGE_CALIBRATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sensor_simulation
{
template <class ContainerAllocator>
struct calibrateRequest_
{
  typedef calibrateRequest_<ContainerAllocator> Type;

  calibrateRequest_()
    : zero(false)  {
    }
  calibrateRequest_(const ContainerAllocator& _alloc)
    : zero(false)  {
  (void)_alloc;
    }



   typedef uint8_t _zero_type;
  _zero_type zero;





  typedef boost::shared_ptr< ::sensor_simulation::calibrateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor_simulation::calibrateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct calibrateRequest_

typedef ::sensor_simulation::calibrateRequest_<std::allocator<void> > calibrateRequest;

typedef boost::shared_ptr< ::sensor_simulation::calibrateRequest > calibrateRequestPtr;
typedef boost::shared_ptr< ::sensor_simulation::calibrateRequest const> calibrateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor_simulation::calibrateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor_simulation::calibrateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sensor_simulation::calibrateRequest_<ContainerAllocator1> & lhs, const ::sensor_simulation::calibrateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.zero == rhs.zero;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sensor_simulation::calibrateRequest_<ContainerAllocator1> & lhs, const ::sensor_simulation::calibrateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sensor_simulation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sensor_simulation::calibrateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_simulation::calibrateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_simulation::calibrateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_simulation::calibrateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_simulation::calibrateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_simulation::calibrateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor_simulation::calibrateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d9ff4c2241c03e6209e4e04727bac371";
  }

  static const char* value(const ::sensor_simulation::calibrateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd9ff4c2241c03e62ULL;
  static const uint64_t static_value2 = 0x09e4e04727bac371ULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor_simulation::calibrateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_simulation/calibrateRequest";
  }

  static const char* value(const ::sensor_simulation::calibrateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor_simulation::calibrateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool zero\n"
;
  }

  static const char* value(const ::sensor_simulation::calibrateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor_simulation::calibrateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.zero);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct calibrateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor_simulation::calibrateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor_simulation::calibrateRequest_<ContainerAllocator>& v)
  {
    s << indent << "zero: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.zero);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_SIMULATION_MESSAGE_CALIBRATEREQUEST_H
