// Generated by gencpp from file sensor_simulation/calibrate.msg
// DO NOT EDIT!


#ifndef SENSOR_SIMULATION_MESSAGE_CALIBRATE_H
#define SENSOR_SIMULATION_MESSAGE_CALIBRATE_H

#include <ros/service_traits.h>


#include <sensor_simulation/calibrateRequest.h>
#include <sensor_simulation/calibrateResponse.h>


namespace sensor_simulation
{

struct calibrate
{

typedef calibrateRequest Request;
typedef calibrateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct calibrate
} // namespace sensor_simulation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sensor_simulation::calibrate > {
  static const char* value()
  {
    return "75b28b77c2f551fa5005ce2f520330b5";
  }

  static const char* value(const ::sensor_simulation::calibrate&) { return value(); }
};

template<>
struct DataType< ::sensor_simulation::calibrate > {
  static const char* value()
  {
    return "sensor_simulation/calibrate";
  }

  static const char* value(const ::sensor_simulation::calibrate&) { return value(); }
};


// service_traits::MD5Sum< ::sensor_simulation::calibrateRequest> should match
// service_traits::MD5Sum< ::sensor_simulation::calibrate >
template<>
struct MD5Sum< ::sensor_simulation::calibrateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sensor_simulation::calibrate >::value();
  }
  static const char* value(const ::sensor_simulation::calibrateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensor_simulation::calibrateRequest> should match
// service_traits::DataType< ::sensor_simulation::calibrate >
template<>
struct DataType< ::sensor_simulation::calibrateRequest>
{
  static const char* value()
  {
    return DataType< ::sensor_simulation::calibrate >::value();
  }
  static const char* value(const ::sensor_simulation::calibrateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sensor_simulation::calibrateResponse> should match
// service_traits::MD5Sum< ::sensor_simulation::calibrate >
template<>
struct MD5Sum< ::sensor_simulation::calibrateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sensor_simulation::calibrate >::value();
  }
  static const char* value(const ::sensor_simulation::calibrateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sensor_simulation::calibrateResponse> should match
// service_traits::DataType< ::sensor_simulation::calibrate >
template<>
struct DataType< ::sensor_simulation::calibrateResponse>
{
  static const char* value()
  {
    return DataType< ::sensor_simulation::calibrate >::value();
  }
  static const char* value(const ::sensor_simulation::calibrateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SENSOR_SIMULATION_MESSAGE_CALIBRATE_H
